# Generated by Django 4.1.7 on 2023-03-06 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Sessão', 'verbose_name_plural': 'Sessões'},
        ),
        migrations.AlterModelOptions(
            name='tip',
            options={'verbose_name': 'Tip', 'verbose_name_plural': 'Tips'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='tip',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='Enviado?'),
        ),
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.plan', verbose_name='Plano'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='bet',
            field=models.CharField(max_length=255, verbose_name='Caderneta BET365'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='game',
            field=models.CharField(max_length=255, verbose_name='Jogo'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='market',
            field=models.CharField(max_length=255, verbose_name='Mercado'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='odd',
            field=models.CharField(max_length=255, verbose_name='Odd'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Está ativo?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='É da equipe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='É super usuário?'),
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, verbose_name='BotFather Token')),
                ('dialog_id', models.IntegerField(verbose_name='ID do Grupo/Canal')),
                ('dialog_name', models.CharField(max_length=255, verbose_name='Nome do Grupo/Canal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Bot',
                'verbose_name_plural': 'Bots',
            },
        ),
    ]
