# Generated by Django 4.1.7 on 2023-03-06 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_session_options_alter_tip_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bot', verbose_name='Bot'),
        ),
    ]
