# Generated by Django 4.1.7 on 2023-03-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tip_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='units',
            field=models.FloatField(default=1, verbose_name='Unidades'),
        ),
    ]
