# Generated by Django 4.1.7 on 2023-03-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tip_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='dialog_id',
            field=models.BigIntegerField(verbose_name='ID do Grupo/Canal'),
        ),
    ]
