# Generated by Django 4.1.7 on 2023-03-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_payment_date_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='payment_date',
            field=models.DateField(null=True, verbose_name='Data de Pagamento'),
        ),
    ]
