# Generated by Django 4.1.7 on 2023-03-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_user_name_alter_user_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='members_qty',
            field=models.IntegerField(default=0, editable=False, verbose_name='Quantidade de membros'),
        ),
        migrations.AddField(
            model_name='user',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Valor da Mensalidade'),
        ),
    ]
