# Generated by Django 4.1.7 on 2023-03-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_bot_members_qty_user_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='house',
            field=models.CharField(choices=[('BET365', 'BET365'), ('BETANO', 'BETANO')], max_length=100, null=True, verbose_name='House'),
        ),
        migrations.AddField(
            model_name='tip',
            name='link',
            field=models.URLField(null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='bet',
            field=models.CharField(max_length=255, null=True, verbose_name='Caderneta BET365'),
        ),
    ]
