# Generated by Django 4.1.7 on 2023-03-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_tip_house_tip_link_alter_tip_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='sum_odds',
            field=models.FloatField(null=True, verbose_name='Soma Odds'),
        ),
    ]
