# Generated by Django 4.1.7 on 2023-03-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_tip_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='create_bet',
            field=models.BooleanField(default=False, verbose_name='É criar aposta?'),
        ),
    ]
