# Generated by Django 4.1.7 on 2023-03-20 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_tip_content_remove_tip_create_bet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='print',
        ),
    ]
