# Generated by Django 4.1.7 on 2023-03-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_tip_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='send_image',
            field=models.BooleanField(default=True, verbose_name='Enviar imagem?'),
        ),
        migrations.AddField(
            model_name='bot',
            name='send_text',
            field=models.BooleanField(default=False, verbose_name='Enviar Texto?'),
        ),
    ]
