# Generated by Django 4.1.7 on 2023-03-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_bot_send_image_bot_send_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='send_image',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='send_text',
        ),
        migrations.AddField(
            model_name='bot',
            name='has_image',
            field=models.BooleanField(default=True, verbose_name='Habilitar imagem?'),
        ),
        migrations.AddField(
            model_name='bot',
            name='has_text',
            field=models.BooleanField(default=False, verbose_name='Habilitar Texto?'),
        ),
        migrations.AddField(
            model_name='bot',
            name='has_watermark',
            field=models.BooleanField(default=False, verbose_name='Habilitar marca da água?'),
        ),
        migrations.AddField(
            model_name='bot',
            name='watermark_alpha',
            field=models.IntegerField(default=50, verbose_name='ALPHA marca da água'),
        ),
        migrations.AddField(
            model_name='bot',
            name='watermark_blue',
            field=models.IntegerField(default=0, verbose_name='BLUE marca da água'),
        ),
        migrations.AddField(
            model_name='bot',
            name='watermark_green',
            field=models.IntegerField(default=0, verbose_name='GREEN marca da água'),
        ),
        migrations.AddField(
            model_name='bot',
            name='watermark_red',
            field=models.IntegerField(default=0, verbose_name='RED marca da água'),
        ),
        migrations.AddField(
            model_name='bot',
            name='watermark_text',
            field=models.CharField(default='@BET365EASY', max_length=100, verbose_name='Texto marca da água'),
        ),
    ]
